.docker/Dockerfile
.docker/requirements.txt
.github/workflows/create-release-tag.yml
source/spark_sql_migrations/setup.py
source/spark_sql_migrations/spark_sql_migrations/current_state/create_current_state.py
source/spark_sql_migrations/spark_sql_migrations/infrastructure/sql_file_executor.py

Bumped Pyspark to 3.5.0
Added some extra prints as well.

Bump Pyspark to 3.5.0

---

.github/workflows/cd.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/create-release-tag.yml
.github/workflows/detect-changes.yml
source/spark_sql_migrations/tests/infrastructure/test_apply_migrations.py

We forgot to change the detect changes for spark SQL migrations at some point.

fix: Detect changes for spark_sql_migrations

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/README.md

Add some documentation for the Spark SQL Migrations package.

docs: Update README Spark SQL Migrations 

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/README.md
source/spark_sql_migrations/spark_sql_migrations/__init__.py
source/spark_sql_migrations/spark_sql_migrations/current_state/create_current_state.py
source/spark_sql_migrations/spark_sql_migrations/models/configuration.py
source/spark_sql_migrations/spark_sql_migrations/models/schema.py
source/spark_sql_migrations/spark_sql_migrations/models/spark_sql_migrations_configuration.py
source/spark_sql_migrations/spark_sql_migrations/models/view.py
source/spark_sql_migrations/tests/builders/spark_sql_migrations_configuration_builder.py
source/spark_sql_migrations/tests/current_state/test_create_current_state.py
source/spark_sql_migrations/tests/helpers/test_schemas.py
source/spark_sql_migrations/tests/test_scripts/view_scripts/script1.sql

Adding Views as configuration for the current state.

feat: Add views folder in current state

---

.github/workflows/pyspark-slim-publish.yml

Fix failed CI step.
Ensure that we get a propper output variable to match the expected input for push of docker image.

Get correct PR state

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/spark_sql_migrations/infrastructure/uncommitted_migration_scripts.py
source/spark_sql_migrations/spark_sql_migrations/utility/catalog_helper.py
source/spark_sql_migrations/tests/utility/test_catalog_helper.py

a minor bug has been found in evaluating if a schema is a unity catalog enabled schema

fix: minor bugfix in unity catalog detection

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/README.md
source/spark_sql_migrations/spark_sql_migrations/current_state/create_current_state.py
source/spark_sql_migrations/spark_sql_migrations/models/spark_sql_migrations_configuration.py
source/spark_sql_migrations/tests/builders/spark_sql_migrations_configuration_builder.py
source/spark_sql_migrations/tests/utility/test_catalog_helper.py

some default values set for locations used by hive_metastore only and support for current_state in unity catalogs
This is clean-up hive_metastore part 1, there will be a part 2 when hive_metastore support is removed totally

feat: Clean up part 1

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/spark_sql_migrations/current_state/create_current_state.py

Checks if current state folders has been addded

fix: fix current_state

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/release-notes/release-notes.md

docs: Create release notes

---

.github/workflows/create-release-tag.yml
.github/workflows/detect-changes.yml
source/spark_sql_migrations/spark_sql_migrations/container.py
source/telemetry/release-notes/release-notes.md

I noticed that the release note was not updated for a couple of releases, so I thought that we should notify the Coder if they did not update the release notes.

 Require Release Notes to be updated

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/README.md
source/spark_sql_migrations/release-notes/release-notes.md
source/spark_sql_migrations/spark_sql_migrations/infrastructure/apply_migration_scripts.py
source/spark_sql_migrations/spark_sql_migrations/models/configuration.py
source/spark_sql_migrations/spark_sql_migrations/models/spark_sql_migrations_configuration.py
source/spark_sql_migrations/tests/builders/spark_sql_migrations_configuration_builder.py
source/spark_sql_migrations/tests/helpers/table_helper.py
source/spark_sql_migrations/tests/infrastructure/test_apply_migration_scripts.py

Requested by Mandalorian.
A configuration parameter to avoid rollback on failure.

feat: Add `rollback_on_failure` configuration parameter

---

.github/workflows/create-release-tag.yml
source/spark_sql_migrations/release-notes/release-notes.md
source/spark_sql_migrations/spark_sql_migrations/schema_migration_pipeline.py
source/spark_sql_migrations/tests/test_schema_migration_pipeline.py
source/telemetry/release-notes/release-notes.md

Added temporary fix that allows migration without current state scripts.

fix:  Added temporary fix that allows migration without current state scripts.

---

.github/workflows/create-release-tag.yml
source/testcommon/release-notes/release-notes.md
source/testcommon/setup.py
source/testcommon/testcommon/dataframes/assert_dataframes.py
source/testcommon/testcommon/dataframes/read_csv.py
source/testcommon/tests/dataframes/test_assert_dataframes_and_schemas.py
source/testcommon/tests/dataframes/test_read_csv.py
source/testcommon/tests/etl/data/then/with_ignored.csv

Added setting ignore_extra_columns_in_actual to the test configuration. If true the IGNORED columns will be ignored.

feat: Added setting ignore_extra_columns_in_actual to test configuration

---

.github/workflows/create-release-tag.yml
source/testcommon/release-notes/release-notes.md
source/testcommon/testcommon/delta_lake/delta_lake_operations.py
source/testcommon/tests/conftest.py
source/testcommon/tests/delta_lake/conftest.py
source/testcommon/tests/delta_lake/test_delta_lake_operations.py

test: Added delta lake operations in testcommon

---

.github/workflows/create-release-tag.yml
source/testcommon/release-notes/release-notes.md
source/testcommon/setup.py
source/testcommon/testcommon/dataframes/__init__.py

Updated init.py to include the write_to_delta file.

fix: Added write_to_delta to init.py

---

.docker/requirements.txt
.github/workflows/create-release-tag.yml
source/testcommon/release-notes/release-notes.md
source/testcommon/setup.py
source/testcommon/testcommon/container_test/__init__.py
source/testcommon/testcommon/container_test/databricks_api_client.py

Adds DatabricksApiClient which can be used to start Databricks jobs in container tests.

feat: Add container test databricks api client

---

.github/workflows/create-release-tag.yml
source/testcommon/README.md
source/testcommon/release-notes/release-notes.md

- Added documentation on how use the scenario_testing functions.

docs: Added scenario testing documentation 

---

.github/workflows/reusable-cd.yml

ci: fix typo in action reference

---

docs/testing/release-notes.md
pyproject.toml
src/geh_common/testing/dataframes/read_csv.py
tests/testing/unit/dataframes/test_read_csv.py

refac: Fix ignored column in scenario test

---

docs/migrations/release-notes.md
pyproject.toml
src/geh_common/migrations/migration_pipeline.py
uv.lock

The import made consumer build fail.

fix: Import in migrations

---

docs/databricks/release-notes.md
pyproject.toml
src/geh_common/databricks/databricks_api_client.py
tests/databricks/test_databricks_api_client.py
uv.lock

We need to cancel job runs. 
- https://github.com/Energinet-DataHub/team-volt/issues/1017

feat: Add cancel job run and get job run to databricks api client

---

.editorconfig

chore: Json indent=2

---

.devcontainer/Dockerfile
.devcontainer/geh_common/devcontainer.json

fix: Devcontainer

---

source/geh_common/pyproject.toml

chore: Don't stop test suite on first test failure

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/domain/types/quantity_unit.py
source/geh_common/uv.lock

remove: `KILO_WATT_HOUR` enum

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/dataframes/logging.py
source/geh_common/tests/testing/unit/dataframes/test_logging.py
source/geh_common/uv.lock

fix: Fix bug in `@testing` decorartor

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/spark/spark_test_session.py

We need to add extra packages in measurements core.

feat: Add `extra_packages` parameter

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_calculated/calculated_measurements_v1.py
source/geh_common/src/geh_common/data_products/measurements_calculated/hourly_calculated_measurements_v1.py
source/geh_common/src/geh_common/data_products/measurements_calculated/missing_measurements_log_v1.py

doc: Add contracts for data products in calculated measurements

---

source/geh_common/pyproject.toml

Update the version number in the project configuration to reflect the new release.

Bump version to 5.6.4

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/capacity_settlement_metering_point_periods_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/electrical_heating_child_metering_points_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/electrical_heating_consumption_metering_point_periods_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/missing_measurements_log_metering_point_periods_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/net_consumption_group_6_child_metering_points_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/net_consumption_group_6_consumption_metering_point_periods_v1.py
source/geh_common/src/geh_common/data_products/measurements_calculated/calculated_measurements_v1.py
source/geh_common/src/geh_common/data_products/measurements_calculated/missing_measurements_log_v1.py
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/current_v1.py
source/geh_common/uv.lock

doc: Added electricity market contracts

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/delta_lake/delta_lake_operations.py
source/geh_common/src/geh_common/testing/spark/spark_test_session.py
source/geh_common/tests/pyspark/unit/test_main.py
source/geh_common/tests/testing/unit/delta_lake/test_delta_lake_operations.py
source/geh_common/uv.lock

Update the version to 5.6.6 and address bugs in the `create_database()` and `create_table()` functions within the `testing.delta_lake` subpackage.

Fix problems in delta helpers

---

source/geh_common/pyproject.toml

chore: reduce delta-spark lock version

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/spark/spark_test_session.py

Related to: https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/734

chore: update docstring in get_spark_test_session

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/electrical_heating_child_metering_points_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/net_consumption_group_6_consumption_metering_point_periods_v1.py

- Removed set notation characters from nsg6 consumption contract

refac: Contract readability

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/dataframes/assert_table.py

Related PR: https://github.com/Energinet-DataHub/opengeh-measurements/pull/728

test: adds function to assert requires table properties

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/missing_measurements_log_metering_point_periods_v1.py

doc: Update documentation of missing_mesasurements_log_v1

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/net_consumption_group_6_child_metering_points_v1.py
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/net_consumption_group_6_consumption_metering_point_periods_v1.py
source/geh_common/uv.lock

refac: Update net_consumption_group_6_child_metering_points_v1 and 

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_measurements_input/missing_measurements_log_metering_point_periods_v1.py

Update documentation of periodization according to SMEs input

doc: Update missing measurements log contract

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/current_v1.py
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/sap_delta_v1.py

View that is used for sap to get delta loads
[1197](https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/gh/energinet-datahub/team-volt/1197)

feat: added sap_delta view

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/infrastructure/write_csv.py

fix: temporary files were not appended correctly

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/infrastructure/write_csv.py

fix: using sets ensures no duplicates

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/application/__init__.py
source/geh_common/src/geh_common/application/retry_policy.py
source/geh_common/tests/application/test_retry_policy.py
source/geh_common/uv.lock

feat: Implement exponential backoff retry policy decorator

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/pyspark/data_frame_wrapper.py
source/geh_common/src/geh_common/telemetry/logger.py
source/geh_common/src/geh_common/telemetry/logging_configuration.py
source/geh_common/tests/telemetry/unit/test_logger.py

fix: Remove bad dependency from telemetry to application

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/dataframes/read_csv.py
source/geh_common/src/geh_common/testing/scenario_testing/TestCases.py
source/geh_common/tests/testing/unit/dataframes/test_read_csv.py
source/geh_common/uv.lock

feat: Added datetime_format to read_csv

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/application/settings.py
source/geh_common/tests/application/test_settings.py

cli_ignore_unknown_args=False

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/testing/dataframes/assert_dataframes.py
source/geh_common/tests/testing/unit/dataframes/test_assert_dataframes_and_schemas.py
source/geh_common/uv.lock

feat: Add enforce row order to assert_dataframes_and_schemas

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/electricity_market_reports_input/measurements_report_metering_point_periods_v1.py

refac: Fix electricity market contract

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/measurements_current_v1.py
source/geh_common/uv.lock

feat: New measurements current v1

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/measurements_current_v1.py
source/geh_common/uv.lock

refac: Update measurement current v1

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_core/measurements_gold/measurements_current_v2.py

feat: Add measurements_current_v2

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/data_products/measurements_calculated/calculated_measurements_including_test_data_v1.py
source/geh_common/src/geh_common/data_products/measurements_calculated/missing_measurements_log_including_test_data_v1.py

We need both contracts that expose test data and contracts that don't.
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/952

feat: Add measurements-calculated contracts that includes test data

---

.github/workflows/ci-orchestrator.yml

Fix duplicate releases being made

Remove duplicate release

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/infrastructure/write_csv.py
source/geh_common/tests/infrastructure/test_write_csv.py

refac: Hide chunk index handling from consumers

---

source/geh_common/pyproject.toml
source/geh_common/release-notes.md
source/geh_common/src/geh_common/infrastructure/write_csv.py
source/geh_common/tests/infrastructure/test_write_csv.py
source/geh_common/uv.lock

- Removed a count that slows down report performance
- Modified the file naming logic to remove the '_1' suffix if only one chunk exists for the partition.
- Added a test for the new naming logic

refac: Removed count and modified file naming logic
